// <auto-generated />
using System;
using Lies.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lies.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615085152_AddMessageFileAttachments")]
    partial class AddMessageFileAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lies.Server.Entities.AccountDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableFunds")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyPnL")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PositionValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("AccountDailies");
                });

            modelBuilder.Entity("Lies.Server.Entities.BankFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("BankFlows");
                });

            modelBuilder.Entity("Lies.Server.Entities.MessageConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_message_preview");

                    b.Property<string>("LastMessageType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("last_message_type");

                    b.Property<string>("PairKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pair_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("PairKey")
                        .IsUnique();

                    b.ToTable("message_conversations");
                });

            modelBuilder.Entity("Lies.Server.Entities.MessageConversationParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("last_read_message_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsPinned");

                    b.ToTable("message_conversation_participants");
                });

            modelBuilder.Entity("Lies.Server.Entities.PortfolioImportAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FinalPayloadJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParseMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ParseSuccess")
                        .HasColumnType("boolean");

                    b.Property<int>("PositionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RecognizedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecognizedPayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("RecognizedText")
                        .HasColumnType("text");

                    b.Property<int>("RequestedTradeCount")
                        .HasColumnType("integer");

                    b.Property<bool>("SaveAttempted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SaveCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaveErrorsJson")
                        .HasColumnType("text");

                    b.Property<string>("SaveMessage")
                        .HasColumnType("text");

                    b.Property<string>("SaveStatus")
                        .HasColumnType("text");

                    b.Property<bool>("SavedAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("SavedBankFlow")
                        .HasColumnType("boolean");

                    b.Property<int>("SavedTradeCount")
                        .HasColumnType("integer");

                    b.Property<bool>("SavedTrades")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredImagePath")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ImportDate");

                    b.HasIndex("SaveStatus");

                    b.HasIndex("UserId");

                    b.ToTable("PortfolioImportAudits");
                });

            modelBuilder.Entity("Lies.Server.Entities.QuickLoginToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selector");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("ValidatorHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("validator_hash");

                    b.HasKey("Id");

                    b.HasIndex("Selector")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("quick_login_tokens");
                });

            modelBuilder.Entity("Lies.Server.Entities.StockBasic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CacheExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StockAbbr")
                        .HasColumnType("text");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StockCode")
                        .IsUnique();

                    b.HasIndex("StockCode", "StockName", "StockAbbr");

                    b.ToTable("StockBasics");
                });

            modelBuilder.Entity("Lies.Server.Entities.StockTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Board")
                        .HasColumnType("integer");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("BuyQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CumulativePnL")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyPnL")
                        .HasColumnType("numeric");

                    b.Property<string>("EmotionTags")
                        .HasColumnType("text");

                    b.Property<bool>("IsLiquidated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PositionPnL")
                        .HasColumnType("numeric");

                    b.Property<int>("PositionQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("SellQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("SellReason")
                        .HasColumnType("text");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TonghuashunLink")
                        .HasColumnType("text");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TradeNote")
                        .HasColumnType("text");

                    b.Property<string>("TradeTags")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TradeDate", "StockCode");

                    b.ToTable("StockTrades");
                });

            modelBuilder.Entity("Lies.Server.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("system_settings");
                });

            modelBuilder.Entity("Lies.Server.Entities.TradeNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StockCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date", "StockCode");

                    b.ToTable("TradeNotes");
                });

            modelBuilder.Entity("Lies.Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Lies.Server.Entities.UserContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.Property<int>("ContactUserId")
                        .HasColumnType("integer")
                        .HasColumnName("contact_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactUserId");

                    b.HasIndex("OwnerUserId", "ContactUserId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "IsPinned");

                    b.ToTable("user_contacts");
                });

            modelBuilder.Entity("Lies.Server.Entities.UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_content_type");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileStoragePath")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("file_storage_path");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_file_name");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recalled");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("message_type");

                    b.Property<DateTime?>("RecalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalled_at");

                    b.Property<int?>("RecalledByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recalled_by_user_id");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("reply_to_message_id");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<string>("TextContent")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text_content");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("SenderUserId", "CreatedAt");

                    b.ToTable("user_messages");
                });

            modelBuilder.Entity("Lies.Server.Entities.AccountDaily", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("AccountDailies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.BankFlow", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("BankFlows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.MessageConversationParticipant", b =>
                {
                    b.HasOne("Lies.Server.Entities.MessageConversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("MessageConversationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.PortfolioImportAudit", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("PortfolioImportAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.QuickLoginToken", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("QuickLoginTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.StockTrade", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("StockTrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.SystemSetting", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedSystemSettings")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Lies.Server.Entities.TradeNote", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "User")
                        .WithMany("TradeNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lies.Server.Entities.UserContact", b =>
                {
                    b.HasOne("Lies.Server.Entities.User", "ContactUser")
                        .WithMany("ContactOfUsers")
                        .HasForeignKey("ContactUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lies.Server.Entities.User", "OwnerUser")
                        .WithMany("OwnedContacts")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactUser");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Lies.Server.Entities.UserMessage", b =>
                {
                    b.HasOne("Lies.Server.Entities.MessageConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lies.Server.Entities.UserMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lies.Server.Entities.User", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Lies.Server.Entities.MessageConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Lies.Server.Entities.User", b =>
                {
                    b.Navigation("AccountDailies");

                    b.Navigation("BankFlows");

                    b.Navigation("ContactOfUsers");

                    b.Navigation("MessageConversationParticipants");

                    b.Navigation("OwnedContacts");

                    b.Navigation("PortfolioImportAudits");

                    b.Navigation("QuickLoginTokens");

                    b.Navigation("SentMessages");

                    b.Navigation("StockTrades");

                    b.Navigation("TradeNotes");

                    b.Navigation("UpdatedSystemSettings");
                });

            modelBuilder.Entity("Lies.Server.Entities.UserMessage", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
